### ISSUE TITLE
Erro libc

### ISSUE THREAD

**Issue by daviDarthemis** [Linux-on-droid/libhybris#1]
Error when trying to find libc bionic

root@localhost:/bin# test_dlopen
library "libc.so" not found
android libc.so is (nil)
root@localhost:/bin#

TERMUX was used with Android 12 root

**Comment by nift4** [comment]
hi, you aren't supposed to use this on termux

**Comment by daviDarthemis** [comment]
Chroot with Ubuntu 23.10
